# Generated by Django 5.1.1 on 2024-10-04 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 10, 4, 12, 49, 54, 903813, tzinfo=datetime.timezone.utc), upload_to='item', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
