# Generated by Django 5.1.1 on 2024-10-04 12:57

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resized_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='item'),
        ),
    ]
