# Generated by Django 5.1.1 on 2024-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes_de',
            field=models.JSONField(null=True, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_en',
            field=models.JSONField(null=True, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_ru',
            field=models.JSONField(null=True, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_uz',
            field=models.JSONField(null=True, verbose_name='Attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
    ]
